### ISSUE TITLE
Transliterator module missing

### ISSUE THREAD

**Issue by IlnarSelimcan** [ftyers/commonvoice-utils#8]
Looks like that you forgot to commit it.

```
~$ python3 -m  pip install git+https://github.com/ftyers/commonvoice-utils.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/ftyers/commonvoice-utils.git
  Cloning https://github.com/ftyers/commonvoice-utils.git to /tmp/pip-req-build-4ptidukg
  Running command git clone -q https://github.com/ftyers/commonvoice-utils.git /tmp/pip-req-build-4ptidukg
Building wheels for collected packages: commonvoice-utils
  Building wheel for commonvoice-utils (setup.py) ... done
  Created wheel for commonvoice-utils: filename=commonvoice_utils-0.2.7-py3-none-any.whl size=142813 sha256=541d42fa2c786d602f4ca04e6f1ad8848a57ded5376f69a19629b1b602577fc7
  Stored in directory: /tmp/pip-ephem-wheel-cache-x_86ocb3/wheels/56/67/73/4bf2d8a681334251a44405673d52e767f646121bbd89c8b7fa
Successfully built commonvoice-utils
Installing collected packages: commonvoice-utils
Successfully installed commonvoice-utils-0.2.7
~$ python3 -c "from cvutils import Alphabet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/selimcan/.local/lib/python3.8/site-packages/cvutils/__init__.py", line 10, in <module>
    from transliterator import Transliterator
ModuleNotFoundError: No module named 'transliterator'
```

I don't think it's this package https://pypi.org/project/transliterator/ that's required ?

**Comment by ftyers** [comment]
You're right I forgot it. I added it in 1b0f914, although I'm not completely satisfied with how it works yet :)

**Comment by IlnarSelimcan** [comment]
Thanks works fine now, this can be closed.
